### ISSUE TITLE
Add an additional handler

### ISSUE THREAD

**Issue by EphraimB** [EphraimB/go-testing-playground#2]
The handler should accept a query string parameter named "search" and the handler should return a json list of search results, this list can be anything for now. You need to add a few tests for this. One for returning a 400 status code if they don't supply the search query string parameter and one for a valid response.

- [x] The handler should return 400 if the `search` query parameter is not provided. write a test for this
- [x] The handler should return a fake list of results in json format. write a test for this

**Comment by sherzberg** [comment]
This was addressed by https://github.com/EphraimB/go-testing-playground/pull/8
